"""Shared constants for ai_risk_gateway."""

from __future__ import annotations

ALLOW = "ALLOW"
REVIEW = "REVIEW"
BLOCK = "BLOCK"

DEFAULT_ALLOW_MAX = 30
DEFAULT_REVIEW_MAX = 60

DEFAULT_FREQUENCY_TIMEFRAME_SECONDS = 3600
DEFAULT_FREQUENCY_MAX_ACTIONS = 5

DEFAULT_DOMAIN_POLICY_WEIGHT = 40
DEFAULT_FREQUENCY_POLICY_WEIGHT = 35
DEFAULT_REFUND_LIMIT_POLICY_WEIGHT = 50