"""Violation model generated by policies."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Violation:
	"""Represents a policy violation with risk contribution."""

	policy_name: str
	message: str
	weight: int
	code: str | None = None
	details: dict[str, Any] = field(default_factory=dict)